# Generated by Django 3.2.6 on 2021-09-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='desc2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
